ALTER TABLE "Project"
  ADD COLUMN IF NOT EXISTS "titleAr" TEXT,
  ADD COLUMN IF NOT EXISTS "descriptionAr" TEXT,
  ADD COLUMN IF NOT EXISTS "clientAr" TEXT,
  ADD COLUMN IF NOT EXISTS "categoryAr" TEXT,
  ADD COLUMN IF NOT EXISTS "tagsAr" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Service"
  ADD COLUMN IF NOT EXISTS "titleAr" TEXT,
  ADD COLUMN IF NOT EXISTS "descriptionAr" TEXT;

ALTER TABLE "TeamMember"
  ADD COLUMN IF NOT EXISTS "nameAr" TEXT,
  ADD COLUMN IF NOT EXISTS "roleAr" TEXT,
  ADD COLUMN IF NOT EXISTS "bioAr" TEXT;

DO $$ BEGIN
  CREATE TYPE "PostStatus" AS ENUM ('DRAFT', 'PUBLISHED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "Post" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "excerpt" TEXT,
  "content" TEXT NOT NULL DEFAULT '',
  "coverImage" TEXT,
  "tags" TEXT[] NOT NULL,
  "status" "PostStatus" NOT NULL DEFAULT 'DRAFT',
  "publishedAt" TIMESTAMP(3),
  "order" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Post_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "Post_slug_key" ON "Post"("slug");

ALTER TABLE "Post"
  ADD COLUMN IF NOT EXISTS "titleAr" TEXT,
  ADD COLUMN IF NOT EXISTS "excerptAr" TEXT,
  ADD COLUMN IF NOT EXISTS "contentAr" TEXT,
  ADD COLUMN IF NOT EXISTS "tagsAr" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "ContactPage"
  ADD COLUMN IF NOT EXISTS "headlineAr" TEXT,
  ADD COLUMN IF NOT EXISTS "subheadlineAr" TEXT,
  ADD COLUMN IF NOT EXISTS "addressAr" TEXT;
