import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database…");

  // Services
  await prisma.service.deleteMany();
  await prisma.service.createMany({
    data: [
      /* ─── 01 Web Development ─── */
      {
        title: "Web Development",
        slug: "web-development",
        titleAr: "تطوير الويب",
        icon: "01",
        order: 1,
        featured: true,
        active: true,
        tagline: "Websites with actual backbone.",
        shortDescription: "We build custom websites, WordPress solutions, landing pages, portfolios, and web experiences that look sharp and actually work. No sleepy templates, no digital cardboard, no homepage that feels like it gave up.",
        description: "<p>Your website should not just exist. It should explain, impress, guide, and quietly make your business look more serious than your email inbox suggests.</p><p>At Nox Studio, we build <strong>custom websites, WordPress websites, portfolio websites, landing pages, business websites, and content-managed platforms</strong> that feel clean, fast, and intentional.</p><p>We mix structure, design, development, and a tiny amount of creative chaos to make websites that feel alive without becoming a circus.</p>",
        descriptionAr: "مواقع وتطبيقات سريعة وقابلة للتوسع مبنية حول الأداء والوضوح والنتائج القابلة للقياس.",
        benefits: [
          "A website that feels custom, not copied",
          "Clearer pages that explain your business better",
          "Easy content control when you need it",
          "Better mobile and desktop experience",
          "Sharper first impression for visitors",
          "Room to grow without rebuilding everything",
        ],
        deliverables: [
          { title: "Custom Website Building", description: "<p>We build full custom websites shaped around your brand, content, services, and goals. The result is a website that feels made for you, not rented from a template neighborhood where every house looks the same.</p><p>This is best for businesses that want a strong digital presence with personality, structure, and long-term flexibility.</p>", icon: "", image: "", highlight: true },
          { title: "Full Custom WordPress Solutions", description: "<p>We turn WordPress into a flexible website system your team can actually manage. That can include editable pages, service sections, project libraries, blogs, offers, forms, custom layouts, and dynamic content areas.</p><p>You get the power of WordPress without the classic “why is this plugin yelling at me?” feeling.</p>", icon: "", image: "", highlight: true },
          { title: "Landing Pages", description: "<p>We create focused landing pages for campaigns, launches, ads, offers, waitlists, and lead generation. Every section has a purpose: explain, convince, build trust, or get the visitor to take action.</p><p>No random filler sections just standing there pretending to help.</p>", icon: "", image: "", highlight: false },
          { title: "Portfolio Websites", description: "<p>We build portfolio websites for studios, creatives, agencies, architects, designers, photographers, and teams that need their work to do the talking. The design gives the projects space to shine without hiding everything behind confusing effects.</p><p>Your work should look curated, not uploaded in a panic.</p>", icon: "", image: "", highlight: false },
          { title: "Business & Company Websites", description: "<p>We build websites for companies, clinics, service providers, consultants, organizations, and growing brands. These websites explain who you are, what you do, why people should trust you, and how they can contact or book with you.</p><p>Basically, your business story, but organized and dressed properly.</p>", icon: "", image: "", highlight: false },
          { title: "Service-Based Websites", description: "<p>We create websites for businesses that sell services, not products. That means strong service pages, clear calls-to-action, FAQs, contact flows, booking options, and trust-building sections.</p><p>If your current service page sounds like it was written during a meeting nobody wanted to attend, we fix that too.</p>", icon: "", image: "", highlight: false },
          { title: "Content-Managed Websites", description: "<p>We build websites where your team can manage services, projects, blogs, testimonials, offers, team members, galleries, and other repeated content from a clean dashboard.</p><p>No more duplicating pages like a forbidden ritual every time you need to add something new.</p>", icon: "", image: "", highlight: false },
          { title: "Booking & Inquiry Websites", description: "<p>We build websites with booking forms, inquiry flows, quote requests, appointment forms, and lead capture systems. The goal is to make it easy for visitors to ask, book, request, or start a conversation.</p><p>Your website should not just say “contact us.” It should help people actually do it.</p>", icon: "", image: "", highlight: false },
          { title: "Web Apps & Client Portals", description: "<p>For projects that need more than pages, we build lightweight web apps, client portals, dashboards, and browser-based systems. These are useful when users need to log in, manage information, submit requests, or interact with your business online.</p><p>This is where the website stops being a brochure and starts doing work.</p>", icon: "", image: "", highlight: false },
          { title: "Website Redesigns", description: "<p>We redesign websites that feel outdated, confusing, slow, or visually tired. We keep what still works, remove what is getting in the way, and rebuild the experience with clearer structure and stronger visuals.</p><p>Not every old website needs a funeral. Some just need a serious glow-up.</p>", icon: "", image: "", highlight: false },
          { title: "Website Launch & Setup", description: "<p>We help prepare the website for launch with domain setup, hosting support, form testing, basic SEO checks, analytics setup, mobile testing, and final polish.</p><p>Launch day should feel like a release, not like everyone is nervously refreshing the browser.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Decode", description: "We understand your business, content, goals, audience, and the real problem hiding behind the sentence: we need a website." },
          { title: "Structure", description: "We plan the pages, sections, user journey, content flow, and what the website needs to do." },
          { title: "Design", description: "We create the visual direction, layouts, and key screens with enough personality to be memorable without becoming weird for no reason." },
          { title: "Build", description: "We develop the website, connect the content system, set up forms, and make sure the experience works across screens." },
          { title: "Test", description: "We test mobile views, links, forms, speed basics, content, and the tiny things that love breaking right before launch." },
          { title: "Launch", description: "We publish the website and make sure everything is ready for real people, not just designers staring at perfect screenshots." },
        ],
        faq: [
          { question: "Do you build WordPress websites?", answer: "<p>Yes. We build WordPress websites ranging from simple editable sites to full custom WordPress solutions with dynamic content, service pages, project libraries, forms, blogs, and custom layouts.</p>" },
          { question: "Do you build custom websites or use templates?", answer: "<p>We focus on custom structure and custom experience. We may use WordPress or helpful tools, but the final result should not feel like a generic template with your logo taped on top.</p>" },
          { question: "Can you build landing pages?", answer: "<p>Yes. We build landing pages for campaigns, launches, services, offers, ads, and lead generation. They are designed to be focused, clear, and conversion-friendly.</p>" },
          { question: "Can I update the website later?", answer: "<p>Yes, when the project needs it. We can set up editable content areas so your team can update text, images, services, projects, posts, and other content without calling us for every comma.</p>" },
          { question: "Can you redesign our existing website?", answer: "<p>Yes. We can redesign the look, improve the structure, rewrite or reorganize content, clean up weak pages, and rebuild the user journey while keeping useful parts from the old site.</p>" },
          { question: "Do you handle launch?", answer: "<p>Yes. We can help with domain setup, hosting, SSL, forms, analytics, Search Console, basic SEO checks, and launch testing.</p>" },
        ],
        ctaHeadline: "Need a sharper website?",
        ctaSubtext: "Bring us the idea, the messy notes, or the folder named final-final-real. We will turn it into a website that feels built, not assembled during a caffeine emergency.",
        ctaButtonLabel: "Start a project",
        ctaButtonLink: "/contact",
        seoTitle: "Web Development Services | Nox Studio",
        seoDescription: "Nox Studio builds custom websites, WordPress websites, landing pages, portfolios, business websites, and web platforms.",
      },

      /* ─── 02 UI/UX Design ─── */
      {
        title: "UI/UX Design",
        slug: "ui-ux-design",
        titleAr: "تصميم الواجهات وتجربة المستخدم",
        icon: "02",
        order: 2,
        featured: true,
        active: true,
        tagline: "Interfaces people can survive.",
        shortDescription: "We design interfaces that look sharp, feel clear, and do not make users question their life choices. Pretty is nice. Pretty that works is better.",
        description: "<p>Good UI is not just beautiful screens floating in space. It is structure, rhythm, clarity, behavior, and knowing when to stop adding things because the user came here to do something.</p><p>We design <strong>websites, apps, dashboards, landing pages, product interfaces, and design systems</strong> that feel polished and usable.</p><p>Our job is to make the experience look creative without turning it into a puzzle box with buttons.</p>",
        descriptionAr: "واجهات وتدفقات منتجات وأنظمة تصميم مبنية على فهم استخدام الناس الفعلي.",
        benefits: [
          "Clearer user journeys",
          "Sharper visual direction",
          "More polished screens",
          "Less confusion for users",
          "Better design consistency",
          "Designs that are easier to build",
        ],
        deliverables: [
          { title: "Website UI Design", description: "<p>We design full website interfaces for homepages, service pages, about pages, portfolios, blogs, contact pages, and landing pages. The design focuses on clarity, hierarchy, and a visual style that does not feel copied from every other agency website.</p><p>Your website should guide people, not make them scroll around like they lost their keys.</p>", icon: "", image: "", highlight: true },
          { title: "Mobile App UI Design", description: "<p>We design mobile app screens that feel clean, focused, and easy to use. That includes onboarding, navigation, forms, cards, profiles, lists, empty states, and all the little screens people actually interact with.</p><p>Small screen, big responsibility.</p>", icon: "", image: "", highlight: true },
          { title: "Landing Page Design", description: "<p>We design landing pages built around one clear goal: leads, signups, bookings, sales, or campaign action. The page gets a strong visual hook, clear message, trust sections, and a path that does not wander into the woods.</p><p>Landing pages should be persuasive, not just long.</p>", icon: "", image: "", highlight: false },
          { title: "Wireframes", description: "<p>We create wireframes to plan the page or app structure before the final visuals. This lets us solve the important layout and flow questions before color, motion, and drama enter the room.</p><p>Wireframes are where the messy idea starts becoming a usable product.</p>", icon: "", image: "", highlight: false },
          { title: "Clickable Prototypes", description: "<p>We create clickable prototypes so you can feel how the website, app, or dashboard moves before development starts. It is easier to fix a confusing flow in design than after someone coded it with tears.</p><p>Useful for apps, dashboards, checkout flows, onboarding, and complex websites.</p>", icon: "", image: "", highlight: false },
          { title: "Dashboard UI Design", description: "<p>We design dashboards, admin panels, CRM screens, tables, filters, status cards, and management views. These screens need to look clean, but more importantly, they need to make work easier.</p><p>A dashboard should not feel like opening the cockpit of a spaceship unless you are actually flying one.</p>", icon: "", image: "", highlight: false },
          { title: "Design Systems", description: "<p>We create reusable styles, components, buttons, cards, typography, colors, spacing, and interaction rules. This keeps the website or product consistent as it grows.</p><p>Without a design system, every new screen slowly becomes its own little country.</p>", icon: "", image: "", highlight: false },
          { title: "UX Audit & Redesign", description: "<p>We review existing websites, apps, or dashboards and identify what feels confusing, outdated, overloaded, or visually weak. Then we redesign the experience to make it clearer and more convincing.</p><p>Sometimes your design does not need more decoration. It needs fewer crimes.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Understand", description: "We study the product, audience, goals, current problems, and what users actually need to do." },
          { title: "Map", description: "We plan the user journey, page flow, screen structure, and important actions." },
          { title: "Wireframe", description: "We create the basic structure before making everything beautiful and suspiciously shiny." },
          { title: "Design", description: "We create the visual interface with typography, spacing, colors, components, and interaction states." },
          { title: "Prototype", description: "We connect key screens so the experience can be reviewed before development starts." },
          { title: "Handoff", description: "We organize the design so developers can build it without needing to decode ancient symbols." },
        ],
        faq: [
          { question: "Do you design only, or also develop?", answer: "<p>We can do both. UI/UX can be delivered as design-only, or it can continue into web development, app development, e-commerce, or CRM systems.</p>" },
          { question: "Do you use Figma?", answer: "<p>Yes. Figma is our main tool for UI design, prototypes, design systems, and developer handoff.</p>" },
          { question: "Can you redesign an existing website or app?", answer: "<p>Yes. We can review the current experience, keep what works, fix what does not, and redesign the screens with better structure and visual direction.</p>" },
          { question: "Do you include mobile design?", answer: "<p>Yes, when the project needs it. Mobile behavior should be designed early, not discovered later when everything starts breaking politely.</p>" },
          { question: "Do you create design systems?", answer: "<p>Yes. For larger websites or products, we create reusable components and visual rules so the design stays consistent as it grows.</p>" },
        ],
        ctaHeadline: "Need cleaner screens?",
        ctaSubtext: "Send us the current design, sketch, or messy idea. We will make it clearer, sharper, and less likely to confuse innocent users.",
        ctaButtonLabel: "Design with us",
        ctaButtonLink: "/contact",
        seoTitle: "UI/UX Design Services | Nox Studio",
        seoDescription: "Nox Studio designs UI/UX for websites, mobile apps, dashboards, landing pages, prototypes, and digital products.",
      },

      /* ─── 03 Mobile Apps ─── */
      {
        title: "Mobile Apps",
        slug: "mobile-apps",
        titleAr: "تطبيقات الجوال",
        icon: "03",
        order: 3,
        featured: false,
        active: true,
        tagline: "Apps that feel intentional.",
        shortDescription: "We design and build mobile app experiences that feel clean, useful, and ready for real users. No mystery buttons, no sad loading screens, no app-store regret.",
        description: "<p>A mobile app needs more than a stack of screens. It needs a reason to exist, a clear journey, useful features, and enough polish to survive living on someone’s phone.</p><p>We help shape <strong>MVPs, service apps, booking apps, customer apps, internal team apps, and app prototypes</strong> from idea to usable product.</p><p>We keep the first version focused so it does not turn into a 78-feature monster wearing a startup hoodie.</p>",
        descriptionAr: "تجارب iOS وAndroid سلسة مع دعم الإطلاق والإشعارات والتحليلات.",
        benefits: [
          "Clear app idea and feature direction",
          "Better mobile user experience",
          "Focused MVP instead of feature chaos",
          "Clean app interface",
          "Useful flows for real users",
          "Room to improve after launch",
        ],
        deliverables: [
          { title: "MVP App Design & Build", description: "<p>We help turn your app idea into a focused first version with the core features users actually need. The goal is not to build everything at once; the goal is to launch something useful without setting the budget on fire.</p><p>Perfect for startups, founders, and businesses testing a new digital product.</p>", icon: "", image: "", highlight: true },
          { title: "Service Booking Apps", description: "<p>We build app experiences for appointments, service bookings, requests, schedules, and customer actions. Users can choose a service, submit details, track status, or complete key steps from their phone.</p><p>Useful for clinics, service providers, education centers, travel companies, and appointment-based businesses.</p>", icon: "", image: "", highlight: true },
          { title: "Customer Portal Apps", description: "<p>We create apps where customers can log in, view their information, submit requests, check progress, receive updates, or manage parts of their relationship with your business.</p><p>It gives your clients a cleaner experience than sending six messages and hoping someone replies with the right PDF.</p>", icon: "", image: "", highlight: false },
          { title: "Internal Team Apps", description: "<p>We build mobile tools for teams that need to manage tasks, requests, field work, clients, notes, checklists, or approvals on the go. Not every app needs to be public; some just need to make the team less chaotic.</p><p>Internal apps are where boring operations become pleasantly less painful.</p>", icon: "", image: "", highlight: false },
          { title: "App UI/UX Design", description: "<p>We design the screens, flow, navigation, onboarding, forms, buttons, empty states, and interactions for your mobile app. The interface should feel clear from the first tap, not like a small puzzle trapped inside glass.</p><p>This can be delivered as design-only or as part of a full app build.</p>", icon: "", image: "", highlight: false },
          { title: "Clickable App Prototypes", description: "<p>We create interactive prototypes so you can test the app idea, show investors, align the team, or validate the flow before development. It makes the app feel real before the expensive part begins.</p><p>Much better than explaining your app with hand gestures and nervous energy.</p>", icon: "", image: "", highlight: false },
          { title: "Admin Panel for Apps", description: "<p>Most apps need a dashboard behind the scenes to manage users, bookings, requests, content, orders, or notifications. We build that control area so your team can operate the app properly.</p><p>The app is what users see. The admin panel is what keeps everyone from panicking.</p>", icon: "", image: "", highlight: false },
          { title: "App Launch Support", description: "<p>We help prepare the app for release with testing, core flow checks, launch assets, store preparation support, and post-launch fixes where needed.</p><p>Because users will always find the one button nobody expected them to press.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Define", description: "We clarify the app idea, audience, main features, and what the first version should actually do." },
          { title: "Simplify", description: "We cut the unnecessary features before they multiply and start demanding their own dashboard." },
          { title: "Design", description: "We design the app screens, flows, and interactions in a way that feels clean and easy to use." },
          { title: "Build", description: "We develop the app experience and connect the parts needed to make it work." },
          { title: "Test", description: "We test core flows, forms, actions, errors, and the weird things real users somehow always do." },
          { title: "Launch", description: "We prepare the app for release and support the first version as it meets the real world." },
        ],
        faq: [
          { question: "Can you build both iOS and Android apps?", answer: "<p>Yes, depending on the project and chosen approach. For many MVPs, a cross-platform build can be the practical choice.</p>" },
          { question: "Can you help us plan the app idea?", answer: "<p>Yes. We can help define the MVP, user flow, features, screens, and launch direction before development starts.</p>" },
          { question: "Do you design the app too?", answer: "<p>Yes. We can handle app UI/UX design, prototypes, and full visual direction before or during the build.</p>" },
          { question: "Can the app have an admin dashboard?", answer: "<p>Yes. Many apps need a dashboard for managing users, bookings, requests, content, orders, or app activity.</p>" },
          { question: "Can you build a prototype first?", answer: "<p>Yes. A clickable prototype is a smart way to test the idea, show stakeholders, and avoid building the wrong thing very confidently.</p>" },
        ],
        ctaHeadline: "Got an app idea?",
        ctaSubtext: "We will help shape it before it grows extra arms and becomes impossible to build. Start focused, launch smarter, improve later.",
        ctaButtonLabel: "Plan your app",
        ctaButtonLink: "/contact",
        seoTitle: "Mobile App Design & Development | Nox Studio",
        seoDescription: "Nox Studio designs and builds mobile apps, MVPs, booking apps, customer portals, prototypes, and app dashboards.",
      },

      /* ─── 04 SEO & Site Health ─── */
      {
        title: "SEO & Site Health",
        slug: "seo-site-health",
        titleAr: "تحسين محركات البحث",
        icon: "04",
        order: 4,
        featured: false,
        active: true,
        tagline: "Fix the invisible damage.",
        shortDescription: "We clean the technical, structural, and content problems that quietly weaken your website. Basically, we check under the digital hood before the engine starts coughing smoke.",
        description: "<p>SEO is not only keywords and blog titles that sound like they were written by a very polite robot. Your site also needs clean structure, healthy pages, proper metadata, fast loading, clear content, and fewer hidden problems.</p><p>We improve <strong>technical SEO, site health, page structure, WordPress SEO, speed basics, analytics, and search visibility foundations</strong>.</p><p>We do not sell SEO fairy dust. We fix what can be found, measured, and improved.</p>",
        descriptionAr: "تدقيق تقني وهيكلة البحث وتخطيط المحتوى واستراتيجية الظهور.",
        benefits: [
          "Cleaner website structure",
          "Better search visibility foundations",
          "Healthier pages and links",
          "Improved speed and user experience",
          "Less hidden technical damage",
          "Clearer SEO priorities",
        ],
        deliverables: [
          { title: "SEO Audit", description: "<p>We review your website and find the issues that may be hurting visibility, structure, performance, or user experience. You get a clear picture of what is broken, weak, missing, or suspiciously dramatic.</p><p>No vague SEO fog. Just problems, priorities, and practical fixes.</p>", icon: "", image: "", highlight: true },
          { title: "Site Health Cleanup", description: "<p>We clean up broken links, weak pages, missing metadata, messy structure, slow sections, duplicate issues, and other problems that make your website harder to trust.</p><p>Think of it as cleaning the digital basement, but with fewer spiders and more redirects.</p>", icon: "", image: "", highlight: true },
          { title: "WordPress SEO Setup", description: "<p>We set up WordPress SEO basics such as page titles, meta descriptions, sitemaps, search settings, schema basics, image optimization, and plugin configuration.</p><p>WordPress gives you power. We help stop it from becoming a plugin jungle with a logo.</p>", icon: "", image: "", highlight: false },
          { title: "On-Page SEO", description: "<p>We improve page titles, headings, descriptions, internal links, image text, content structure, and the way each page explains itself to both users and search engines.</p><p>Good on-page SEO is not stuffing keywords until the page sounds haunted.</p>", icon: "", image: "", highlight: false },
          { title: "Website Speed Cleanup", description: "<p>We review heavy images, slow pages, unnecessary bloat, loading issues, and common speed problems. Faster websites feel better, convert better, and complain less.</p><p>A slow website is basically a waiting room with a logo.</p>", icon: "", image: "", highlight: false },
          { title: "Content Structure Improvement", description: "<p>We reorganize content so pages are easier to read, scan, understand, and index. This is useful for service pages, blogs, product categories, case studies, and websites that grew in every direction at once.</p><p>Search engines like structure. Humans do too, even if they do not say it out loud.</p>", icon: "", image: "", highlight: false },
          { title: "Local SEO Basics", description: "<p>For location-based businesses, we help improve local search foundations such as location pages, business information, service areas, map signals, and locally relevant content.</p><p>If people nearby are searching, your website should not be hiding like it owes them money.</p>", icon: "", image: "", highlight: false },
          { title: "Analytics & Search Console Setup", description: "<p>We help set up or review Google Analytics, Search Console, tracking basics, and performance signals. You should know what is happening on your website instead of reading traffic numbers like tea leaves.</p><p>Better tracking means better decisions and fewer guesses wearing a business suit.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Audit", description: "We inspect the website structure, pages, metadata, speed, links, content, and search setup." },
          { title: "Prioritize", description: "We separate urgent problems from nice-to-have fixes so the work does not become an endless spreadsheet swamp." },
          { title: "Clean", description: "We fix the important issues, improve page structure, and remove avoidable obstacles." },
          { title: "Improve", description: "We enhance metadata, content structure, internal links, speed basics, and search-friendly elements." },
          { title: "Track", description: "We set up or review analytics and search tools so improvements can be monitored." },
        ],
        faq: [
          { question: "Can you guarantee first-page rankings?", answer: "<p>No. Nobody serious should promise that casually. We focus on improving the technical and content foundations that support better search performance.</p>" },
          { question: "Do you work on WordPress SEO?", answer: "<p>Yes. We can work with WordPress, Elementor, Rank Math, Yoast, WooCommerce, blogs, service pages, and technical setup issues.</p>" },
          { question: "Do you only provide a report?", answer: "<p>We can provide an audit, implement fixes, or do both. Some clients want the map. Others want us to bring the tools and clean the mess.</p>" },
          { question: "How long does SEO take?", answer: "<p>Technical improvements can happen quickly, but search results usually take time. It depends on competition, content, authority, indexing, and the current state of the website.</p>" },
          { question: "Can you improve website speed?", answer: "<p>Yes. We can review images, scripts, plugins, loading behavior, and common performance issues to make the site feel cleaner and faster.</p>" },
        ],
        ctaHeadline: "Is your site healthy?",
        ctaSubtext: "Let us inspect the weird stuff hiding behind the pretty homepage. We will tell you what matters, what is broken, and what is just SEO theater.",
        ctaButtonLabel: "Check my site",
        ctaButtonLink: "/contact",
        seoTitle: "SEO & Site Health Services | Nox Studio",
        seoDescription: "Nox Studio improves SEO, site health, WordPress SEO, speed, content structure, analytics, and search visibility.",
      },

      /* ─── 05 CRM Systems ─── */
      {
        title: "CRM Systems",
        slug: "crm-systems",
        titleAr: "إدارة علاقات العملاء",
        icon: "05",
        order: 5,
        featured: false,
        active: true,
        tagline: "Stop managing chaos manually.",
        shortDescription: "We build CRM systems, dashboards, and workflows that help teams track leads, clients, bookings, tasks, and follow-ups without living inside scattered chats and spreadsheets.",
        description: "<p>If your business process lives across WhatsApp, Excel, sticky notes, memory, and one person who knows everything, you do not have a system. You have a hostage situation.</p><p>We build <strong>custom CRMs, lead tracking systems, booking dashboards, client portals, internal tools, and workflow systems</strong> that make operations visible and manageable.</p><p>Nox Studio builds systems that make your team look calmer than they actually are.</p>",
        descriptionAr: "منصات تشغيل مخصصة للحجوزات والفرق والتقارير وسير العمل.",
        benefits: [
          "Better lead tracking",
          "Cleaner customer management",
          "Less manual follow-up chaos",
          "Clearer team workflows",
          "Centralized business information",
          "Dashboards built around your process",
        ],
        deliverables: [
          { title: "Custom CRM Systems", description: "<p>We build CRM systems around your real workflow, not around a generic tool that expects your business to behave differently. You can track leads, clients, requests, statuses, notes, and team actions in one organized place.</p><p>It is like giving your operations a brain, but without making it wear a tie.</p>", icon: "", image: "", highlight: true },
          { title: "Lead Tracking Dashboards", description: "<p>We create dashboards where your team can see new leads, follow-ups, statuses, sources, assigned team members, and next actions. This helps stop good opportunities from disappearing into the chat-history graveyard.</p><p>If someone asks “did we follow up?” the system should answer before the room gets awkward.</p>", icon: "", image: "", highlight: true },
          { title: "Booking Management Systems", description: "<p>We build systems for managing appointments, consultations, service bookings, requests, and schedule-related workflows. Each booking can move through clear stages from new request to confirmed, completed, cancelled, or whatever your process needs.</p><p>Useful for clinics, service providers, education centers, agencies, and appointment-heavy businesses.</p>", icon: "", image: "", highlight: false },
          { title: "Client Portals", description: "<p>We create portals where clients can log in, view information, submit requests, check status, access files, or manage parts of their relationship with your business.</p><p>It gives clients a cleaner place to go instead of asking the same question in three different channels.</p>", icon: "", image: "", highlight: false },
          { title: "Internal Team Dashboards", description: "<p>We build internal dashboards for teams to manage tasks, clients, requests, approvals, notes, content, or daily work. These tools are designed around how your team actually operates.</p><p>The goal is less “where is that file?” and more “oh, there it is.”</p>", icon: "", image: "", highlight: false },
          { title: "Follow-Up Systems", description: "<p>We build follow-up flows with statuses, reminders, notes, next actions, and team assignments. This helps your team know who needs attention and when.</p><p>Follow-up should not depend on memory, vibes, or a notebook hiding under a keyboard.</p>", icon: "", image: "", highlight: false },
          { title: "CRM for WordPress Websites", description: "<p>For some projects, we can build CRM-like dashboards inside WordPress using custom content, user roles, forms, statuses, and admin views. This is useful when the CRM is closely connected to the website.</p><p>WordPress can do more than pages when it is not left unsupervised.</p>", icon: "", image: "", highlight: false },
          { title: "Automated Notifications", description: "<p>We set up useful notifications for new leads, booking changes, status updates, assigned tasks, or form submissions. The goal is to notify people at the right moment, not create a robot that screams all day.</p><p>Good automation makes the team faster without making everyone hate their inbox.</p>", icon: "", image: "", highlight: false },
          { title: "Reports & Activity Views", description: "<p>We create simple reports and views for leads, bookings, statuses, team activity, request volume, and other useful numbers. No fake business-intelligence theater, just information that helps decisions.</p><p>Charts are nice. Knowing what is happening is better.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Map", description: "We study how your team receives, handles, follows up, and closes leads, bookings, clients, or requests." },
          { title: "Organize", description: "We define the fields, statuses, users, actions, dashboard views, and workflow rules." },
          { title: "Design", description: "We design a dashboard that is clear enough to use daily without emotional preparation." },
          { title: "Build", description: "We build the CRM, dashboards, forms, client views, notifications, and workflow logic." },
          { title: "Test", description: "We test the real workflow from new lead or request to final status, including the messy cases." },
          { title: "Improve", description: "We adjust the system after real use reveals what your workflow actually needs." },
        ],
        faq: [
          { question: "Do we need a custom CRM?", answer: "<p>If your process is simple, an existing CRM might be enough. If your workflow is specific, messy, or tied to your website, a custom CRM can make more sense.</p>" },
          { question: "Can the CRM connect to our website forms?", answer: "<p>Yes. Website forms can send leads, bookings, applications, or requests directly into the CRM with statuses and notifications.</p>" },
          { question: "Can you build CRM features inside WordPress?", answer: "<p>Yes. For many use cases, WordPress can support custom dashboards, lead tracking, booking workflows, admin views, and user roles.</p>" },
          { question: "Can different team members have different access?", answer: "<p>Yes. We can create role-based access so each team member sees the parts they need and avoids the scary buttons.</p>" },
          { question: "Can the system send emails or notifications?", answer: "<p>Yes. We can add notifications for new requests, status changes, follow-ups, assigned tasks, and other workflow events.</p>" },
        ],
        ctaHeadline: "Need a real system?",
        ctaSubtext: "Show us your current workflow, even if it is ugly. Especially if it is ugly. That is where useful systems usually begin.",
        ctaButtonLabel: "Build my CRM",
        ctaButtonLink: "/contact",
        seoTitle: "Custom CRM Systems | Nox Studio",
        seoDescription: "Nox Studio builds custom CRM systems, lead dashboards, booking systems, client portals, workflows, and internal tools.",
      },

      /* ─── 06 E-commerce ─── */
      {
        title: "E-commerce",
        slug: "ecommerce",
        titleAr: "التجارة الإلكترونية",
        icon: "06",
        order: 6,
        featured: false,
        active: true,
        tagline: "Stores that sell without begging.",
        shortDescription: "We build e-commerce websites that make products easier to browse, trust, and buy. Less clutter, better product flow, and fewer checkout moments that feel like paperwork.",
        description: "<p>An online store is not just products in boxes. It is product discovery, trust, browsing, cart behavior, checkout flow, mobile experience, and the delicate art of asking for money without annoying everyone.</p><p>We build <strong>WooCommerce stores, custom online shops, product catalogs, cart experiences, checkout flows, and store redesigns</strong>.</p><p>Your store should feel like a good salesperson, not a warehouse with Wi-Fi.</p>",
        descriptionAr: "متاجر تركز على التحويل مع الدفع والتحليلات وأسس النمو.",
        benefits: [
          "Cleaner product browsing",
          "Better product presentation",
          "Smoother cart and checkout flow",
          "Mobile-friendly shopping experience",
          "Stronger customer trust",
          "Easier store management",
        ],
        deliverables: [
          { title: "Custom Online Stores", description: "<p>We build online stores that match your brand, products, and customer journey. The store should feel intentional, not like a default theme that discovered your logo five minutes ago.</p><p>Best for brands that want a polished shopping experience with a clear structure and stronger visual identity.</p>", icon: "", image: "", highlight: true },
          { title: "WooCommerce Stores", description: "<p>We build WooCommerce stores for businesses that want e-commerce inside WordPress. That can include products, categories, variations, coupons, checkout, payments, shipping, and editable store pages.</p><p>WooCommerce is powerful when it is planned properly and not treated like a plugin buffet.</p>", icon: "", image: "", highlight: true },
          { title: "Product Catalog Websites", description: "<p>We create product catalog websites for businesses that want to showcase products without necessarily selling directly online. Products can be organized by category, type, collection, brand, or custom filters.</p><p>Perfect when your products need to be browsed, compared, requested, or quoted.</p>", icon: "", image: "", highlight: false },
          { title: "Product Pages", description: "<p>We design product pages with clear images, descriptions, pricing, options, trust details, and calls-to-action. A good product page answers questions before the customer runs away to compare prices elsewhere.</p><p>The page should help people decide, not send them into detective mode.</p>", icon: "", image: "", highlight: false },
          { title: "Collection & Category Pages", description: "<p>We build clean category and collection pages with product cards, filters, sorting, featured items, and browsing structure. Customers should find what they need without feeling like they entered a maze with a shopping cart.</p><p>Good browsing makes the store feel larger, clearer, and easier to trust.</p>", icon: "", image: "", highlight: false },
          { title: "Cart & Checkout Experience", description: "<p>We improve the cart and checkout flow so customers can review, adjust, and complete orders with less friction. This includes checkout layout, payment clarity, order summaries, coupon behavior, and mobile usability.</p><p>The checkout should not feel like a tax form wearing lipstick.</p>", icon: "", image: "", highlight: false },
          { title: "Store Redesigns", description: "<p>We redesign online stores that feel outdated, confusing, cluttered, or hard to shop from. We improve the visual direction, product flow, browsing experience, and checkout clarity.</p><p>Sometimes the products are good, but the store is making them look suspicious.</p>", icon: "", image: "", highlight: false },
          { title: "Offers, Coupons & Campaign Pages", description: "<p>We build promotional sections, coupon setups, offer pages, bundles, sale areas, and campaign landing pages. This helps your store support marketing without manually rebuilding everything every time there is a new offer.</p><p>Discounts should feel strategic, not like someone panicked near a price field.</p>", icon: "", image: "", highlight: false },
          { title: "Store Management Setup", description: "<p>We set up the backend so your team can manage products, orders, categories, images, stock, coupons, and basic store content. The admin side should feel manageable, not like opening a control panel for a submarine.</p><p>A good store is not only nice for customers; it is also usable for the people running it.</p>", icon: "", image: "", highlight: false },
        ],
        process: [
          { title: "Study", description: "We understand your products, customers, buying behavior, and what makes people hesitate before purchase." },
          { title: "Structure", description: "We plan product categories, product pages, browsing flow, cart behavior, and checkout needs." },
          { title: "Design", description: "We design the store experience so products feel clear, trustworthy, and easy to explore." },
          { title: "Build", description: "We build the store, product pages, category pages, cart, checkout, and backend management setup." },
          { title: "Test", description: "We test browsing, product options, cart updates, checkout, payments, emails, and mobile behavior." },
          { title: "Launch", description: "We launch the store and check the first real shopping experience before the internet starts touching things." },
        ],
        faq: [
          { question: "Do you build WooCommerce stores?", answer: "<p>Yes. We build WooCommerce stores with products, categories, variations, cart, checkout, payment setup, shipping, coupons, and custom layouts.</p>" },
          { question: "Can you redesign an existing store?", answer: "<p>Yes. We can improve the look, product pages, browsing flow, cart, checkout, and mobile shopping experience while keeping useful existing store data.</p>" },
          { question: "Can the store support product variations?", answer: "<p>Yes. We can set up sizes, colors, materials, packages, options, stock, and other product variations depending on your catalog.</p>" },
          { question: "Can you set up payments?", answer: "<p>Yes, depending on the payment provider and region. We can help connect payment gateways and test the checkout process.</p>" },
          { question: "Do you build product catalog websites too?", answer: "<p>Yes. If you do not want direct checkout, we can build a catalog website where users browse products and send inquiries or quote requests.</p>" },
        ],
        ctaHeadline: "Ready to sell better?",
        ctaSubtext: "Let us build a store that makes products easier to trust and buy. No sad carts. No confusing checkout caves.",
        ctaButtonLabel: "Build my store",
        ctaButtonLink: "/contact",
        seoTitle: "E-commerce Website Design | Nox Studio",
        seoDescription: "Nox Studio builds WooCommerce stores, custom online shops, product catalogs, product pages, carts, and checkout flows.",
      },
    ],
  });

  // Projects
  await prisma.project.deleteMany();
  await prisma.project.createMany({
    data: [
      {
        slug: "elia-clinic",
        title: "Elia Clinic",
        titleAr: "عيادة إيليا",
        description: "A calm, conversion-led medical site with a modular content system and refined motion.",
        descriptionAr: "موقع طبي هادئ يركز على التحويل مع نظام محتوى مرن وحركة دقيقة.",
        client: "Elia Medical Group",
        clientAr: "مجموعة إيليا الطبية",
        year: "2025",
        category: "Healthcare",
        categoryAr: "الرعاية الصحية",
        tags: ["Web Design", "Motion", "CMS"],
        tagsAr: ["تصميم الويب", "الحركة", "إدارة المحتوى"],
        coverImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80&auto=format&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80",
          "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=80",
        ],
        featured: true,
        order: 1,
        status: "PUBLISHED",
      },
      {
        slug: "montgab",
        title: "Montgab",
        titleAr: "مونتغاب",
        description: "A tactile storefront balancing product storytelling, speed, and editorial whitespace.",
        descriptionAr: "متجر يجمع بين سرد المنتج والسرعة والمساحات التحريرية.",
        client: "Montgab Collective",
        clientAr: "مجموعة مونتغاب",
        year: "2025",
        category: "E-Commerce",
        categoryAr: "التجارة الإلكترونية",
        tags: ["E-Commerce", "UI/UX", "Shopify"],
        tagsAr: ["التجارة الإلكترونية", "تجربة المستخدم", "Shopify"],
        coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80&auto=format&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80",
          "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1200&q=80",
        ],
        featured: true,
        order: 2,
        status: "PUBLISHED",
      },
      {
        slug: "180-degrees",
        title: "180 Degrees",
        titleAr: "180 درجة",
        description: "A flexible studio identity translated into web, motion, and campaign surfaces.",
        descriptionAr: "هوية استوديو مرنة مترجمة إلى الويب والحركة والحملات.",
        client: "180 Degrees Studio",
        clientAr: "استوديو 180 درجة",
        year: "2026",
        category: "Agency / Brand",
        categoryAr: "وكالة / علامة تجارية",
        tags: ["Branding", "Motion", "Web"],
        tagsAr: ["العلامة التجارية", "الحركة", "الويب"],
        coverImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80&auto=format&fit=crop",
        images: ["https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80"],
        featured: false,
        order: 3,
        status: "PUBLISHED",
      },
      {
        slug: "launchpad",
        title: "Launchpad",
        titleAr: "لانشباد",
        description: "A developer-focused SaaS dashboard built for speed, clarity, and team collaboration.",
        descriptionAr: "لوحة منصة برمجية للمطورين مبنية للسرعة والوضوح والتعاون.",
        client: "Launchpad Inc.",
        clientAr: "لانشباد",
        year: "2026",
        category: "SaaS Platform",
        categoryAr: "منصة برمجية",
        tags: ["SaaS", "Dashboard", "Next.js"],
        tagsAr: ["SaaS", "لوحة تحكم", "Next.js"],
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80&auto=format&fit=crop",
        images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80"],
        featured: false,
        order: 4,
        status: "PUBLISHED",
      },
    ],
  });

  // Tech Library — only seed if empty (preserves any custom icon uploads)
  const techCount = await prisma.techItem.count();
  if (techCount === 0) {
    const SI = "https://cdn.simpleicons.org";
    await prisma.techItem.createMany({
      data: [
        { name: "Next.js",         icon: "⚡", iconUrl: `${SI}/nextdotjs`,      order: 1  },
        { name: "React",           icon: "⚛️", iconUrl: `${SI}/react`,           order: 2  },
        { name: "TypeScript",      icon: "🔷", iconUrl: `${SI}/typescript`,      order: 3  },
        { name: "JavaScript",      icon: "🟡", iconUrl: `${SI}/javascript`,      order: 4  },
        { name: "Node.js",         icon: "🟢", iconUrl: `${SI}/nodedotjs`,       order: 5  },
        { name: "Tailwind CSS",    icon: "🎨", iconUrl: `${SI}/tailwindcss`,     order: 6  },
        { name: "PostgreSQL",      icon: "🐘", iconUrl: `${SI}/postgresql`,      order: 7  },
        { name: "Prisma",          icon: "🔺", iconUrl: `${SI}/prisma`,          order: 8  },
        { name: "GraphQL",         icon: "🔴", iconUrl: `${SI}/graphql`,         order: 9  },
        { name: "Vercel",          icon: "▲",  iconUrl: `${SI}/vercel`,          order: 10 },
        { name: "AWS",             icon: "☁️", iconUrl: `${SI}/amazonaws`,       order: 11 },
        { name: "Docker",          icon: "🐳", iconUrl: `${SI}/docker`,          order: 12 },
        { name: "Figma",           icon: "🎯", iconUrl: `${SI}/figma`,           order: 13 },
        { name: "Shopify",         icon: "🛍️", iconUrl: `${SI}/shopify`,         order: 14 },
        { name: "Stripe",          icon: "💳", iconUrl: `${SI}/stripe`,          order: 15 },
        { name: "Supabase",        icon: "⚡", iconUrl: `${SI}/supabase`,        order: 16 },
        { name: "Redis",           icon: "🔴", iconUrl: `${SI}/redis`,           order: 17 },
        { name: "MongoDB",         icon: "🍃", iconUrl: `${SI}/mongodb`,         order: 18 },
        { name: "Python",          icon: "🐍", iconUrl: `${SI}/python`,          order: 19 },
        { name: "Vue.js",          icon: "💚", iconUrl: `${SI}/vuedotjs`,        order: 20 },
        { name: "Svelte",          icon: "🔥", iconUrl: `${SI}/svelte`,          order: 21 },
        { name: "Astro",           icon: "🚀", iconUrl: `${SI}/astro`,           order: 22 },
        { name: "Three.js",        icon: "🎲", iconUrl: `${SI}/threedotjs`,      order: 23 },
        { name: "GSAP",            icon: "🟢", iconUrl: `${SI}/greensock`,       order: 24 },
        { name: "Framer Motion",   icon: "🌀", iconUrl: `${SI}/framer`,          order: 25 },
        { name: "Sanity",          icon: "🟥", iconUrl: `${SI}/sanity`,          order: 26 },
        { name: "Contentful",      icon: "🔵", iconUrl: `${SI}/contentful`,      order: 27 },
        { name: "Cloudinary",      icon: "☁️", iconUrl: `${SI}/cloudinary`,      order: 28 },
        { name: "Firebase",        icon: "🔥", iconUrl: `${SI}/firebase`,        order: 29 },
        { name: "Cloudflare",      icon: "🌐", iconUrl: `${SI}/cloudflare`,      order: 30 },
        { name: "Webflow",         icon: "🌊", iconUrl: `${SI}/webflow`,         order: 31 },
        { name: "WordPress",       icon: "🔵", iconUrl: `${SI}/wordpress`,       order: 32 },
        { name: "React Native",    icon: "📱", iconUrl: `${SI}/react`,           order: 33 },
        { name: "Expo",            icon: "📱", iconUrl: `${SI}/expo`,            order: 34 },
        { name: "GitHub Actions",  icon: "🔄", iconUrl: `${SI}/githubactions`,   order: 35 },
      ],
    });
    console.log("✓ Tech library seeded (35 items)");
  } else {
    console.log(`↩ Tech library skipped (${techCount} items already exist)`);
  }

  console.log("✓ Seed complete");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
